modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Rasa-Novum/runeweaver/issues"

[[mods]]
modId = "runeweaver"
version = "${version}"
displayName = "Runeweaver"
logoFile = "logo.png"
authors = "Ramixin, xameryn"
description = '''
Allows in-code manipulation of asset/data resources
'''

[[dependencies.runeweaver]]
modId = "neoforge"
type = "required"
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.runeweaver]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "runeweaver.mixins.json"
